expenditure_personal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('load_amount.urls', namespace='index')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('listall/', include('all_view.urls', namespace='all_view')),
    path('expense/', include('load_amount.urls', namespace='amount')),
    path('income/', include('income.urls', namespace='income')),
    path('chain/', include('chain.urls', namespace='chain')),
    path('loan/', include('loan.urls', namespace='loan')),
    path('returns/', include('returns.urls', namespace='returns')),
    path('reversal/', include('reversal.urls', namespace='reversal')),
    path('credits/', include('user.urls', namespace='credits')),
    path('expwith/', include('cashwithdrawl.urls', namespace='expwith'))
]

loan/urls.py
from django.urls import path
from .views import loan_data, update, loan_dropdown

app_name = 'loan'

urlpatterns = [
    path('', loan_data, name='loan_data'),
    path('loans/<int:id>/', update, name='update_loan_data'),
    path('dropdown/', loan_dropdown, name='dropwn_loan')
]

reversal/urls.py
from django.urls import path
from . import views

app_name = 'reversal'

urlpatterns = [
    path('', views.form_data, name='reversal'),
    path('reversal/<int:id>/', views.update, name='update_reversal'),
]

reversal/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Reversal(models.Model):

    chain_link = models.ForeignKey('chain.ChainModel', on_delete=models.CASCADE, related_name='reverse_chain_link', default=None,
                                    null=True, blank=True)
    loan_link = models.ForeignKey('loan.loan', on_delete=models.CASCADE, related_name='reverse_loan_link', default=None,
                                    null=True, blank=True)
    income_link = models.ForeignKey('income.Income', on_delete=models.CASCADE, related_name='reverse_income_link', default=None,
                                  null=True, blank=True)
    returns_link = models.ForeignKey('returns.Returns', on_delete=models.CASCADE, related_name='reversal_returns_link', default=None,
                                  null=True, blank=True)
    reversal_amount = models.PositiveIntegerField()
    source_link = models.CharField(max_length=10, choices=settings.SELECT_LINK, default=settings.SELECT_LINK[1][0])
    description = models.CharField(max_length=200, default=None, null=True)
    purchase_date = models.DateField()
    reversal_loan = models.ForeignKey('loan.loan', on_delete=models.CASCADE, related_name='reverse_reversal_loan_link', default=None,
                                  null=True, blank=True)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return str(self.id)

reversal/forms.py
from django import forms
from .models import Reversal

class ReversalForm(forms.ModelForm):
    class Meta:
        model = Reversal
        fields = ['reversal_amount', 'source_link', 'chain_link', 'loan_link', 'income_link', 'returns_link',
                  'description', 'purchase_date', 'reversal_loan']

reversal/views.py
from django.shortcuts import render
from .forms import ReversalForm
from .models import Reversal
from user.models import UserProfile
from django.http import JsonResponse
from all_view.views import all_list_rest
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def form_data(request):
    user = UserProfile.objects.get(user_id=request.user.id)
    if request.method == "POST":
        form = ReversalForm(request.POST)
        if form.is_valid():
            user.commits += 1
            user.save()
            form.save()
            return HttpResponseRedirect('/listall')
    else:
        form = ReversalForm()
    income_form, load_form, chain_form, loan_form, returns_form = all_list_rest()
    return render(request,'app/reversal.html',{'form':form, 'income_form':income_form, 'load_form':load_form,
                                                   'chain_form':chain_form, 'loan_form': loan_form,'returns_form':returns_form})


def update(request, id):
    data = Reversal.objects.get(id=id)
    data.reversal_amount = request.POST['reversal_amount']
    data.purchase_date = request.POST['purchase_date']
    data.description = request.POST['description']
    data.save()
    return HttpResponse('updated')

reversal/templates/app/reversal.html
{% extends "load_base.html" %}

{% block title %}Load Reversal{% endblock %}

{% block content %}
    <h1> Load new reversal </h1>
    <form action="/reversal/" method="post" id="expense" novalidate>
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="submit">
    </form>

    <script type = "text/javascript">
        $(document).ready(function() {
            $('label[for="id_chain_link"]').hide();$("#id_chain_link").hide();
            $('label[for="id_loan_link"]').show();$("#id_loan_link").show();
            $('label[for="id_income_link"]').hide();$("#id_income_link").hide();
            $('label[for="id_returns_link"]').hide();$("#id_returns_link").hide();
         });
        $('#id_source_link').on('change',function(){
            if( $(this).val()==="income"){
               $('label[for="id_chain_link"]').hide();$("#id_chain_link").hide();
               $('label[for="id_loan_link"]').hide();$("#id_loan_link").hide();
               $('label[for="id_income_link"]').show();$("#id_income_link").show();
               $('label[for="id_returns_link"]').hide();$("#id_returns_link").hide();
            } else if( $(this).val()==="chain"){
               $('label[for="id_chain_link"]').show();$("#id_chain_link").show();
               $('label[for="id_loan_link"]').hide();$("#id_loan_link").hide();
               $('label[for="id_income_link"]').hide();$("#id_income_link").hide();
               $('label[for="id_returns_link"]').hide();$("#id_returns_link").hide();
            } else if( $(this).val()==="loan"){
               $('label[for="id_chain_link"]').hide();$("#id_chain_link").hide();
               $('label[for="id_loan_link"]').show();$("#id_loan_link").show();
               $('label[for="id_income_link"]').hide();$("#id_income_link").hide();
               $('label[for="id_returns_link"]').hide();$("#id_returns_link").hide();
            } else if( $(this).val()==="returns"){
               $('label[for="id_chain_link"]').hide();$("#id_chain_link").hide();
               $('label[for="id_loan_link"]').hide();$("#id_loan_link").hide();
               $('label[for="id_income_link"]').hide();$("#id_income_link").hide();
               $('label[for="id_returns_link"]').show();$("#id_returns_link").show();
            }
        });
    </script>
{% endblock %}