expenditure_personal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('load_amount.urls', namespace='index')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('listall/', include('all_view.urls', namespace='all_view')),
    path('expense/', include('load_amount.urls', namespace='amount')),
    path('income/', include('income.urls', namespace='income')),
    path('chain/', include('chain.urls', namespace='chain')),
    path('loan/', include('loan.urls', namespace='loan')),
    path('returns/', include('returns.urls', namespace='returns')),
    path('reversal/', include('reversal.urls', namespace='reversal')),
    path('credits/', include('user.urls', namespace='credits')),
    path('expwith/', include('cashwithdrawl.urls', namespace='expwith'))
]

load_amount/urls.py
from django.urls import path
from . import views

app_name = 'load_amount'

urlpatterns = [
    path('', views.index, name='get_data'),
    path('load_expense/', views.form_data, name='load_expense'),
    path('load_expense/<int:id>/', views.update, name='load_expense')
]

loan/urls.py
from django.urls import path
from .views import loan_data, update, loan_dropdown

app_name = 'loan'

urlpatterns = [
    path('', loan_data, name='loan_data'),
    path('loans/<int:id>/', update, name='update_loan_data'),
    path('dropdown/', loan_dropdown, name='dropwn_loan')
]

load_amount/models.py
from django.db import models
from income.models import Income
from chain.models import ChainModel
from loan.models import loan
from django.conf import settings
# Create your models here.


class Money(models.Model):
    loan_link = models.ForeignKey('loan.loan', on_delete=models.CASCADE, related_name='loan_related',
                                   default=None, null=True, blank=True)
    chain_link = models.ForeignKey('chain.ChainModel', on_delete=models.CASCADE, related_name='chain_income',
                                   default=None, null=True, blank=True)
    income_link = models.ForeignKey('income.Income', on_delete=models.CASCADE, related_name='income', default=None,
                                    null=True, blank=True)
    returns_link = models.ForeignKey('returns.Returns', on_delete=models.CASCADE, related_name='reverse_returns_link',
                                     default=None,
                                     null=True, blank=True)
    withdraw_link = models.ForeignKey('cashwithdrawl.CashWithdrawl', on_delete=models.CASCADE, related_name='cashwithdrawl_link',
                                     default=None,
                                     null=True, blank=True)
    expense_link = models.CharField(max_length=10, choices=settings.SOURCE, default=settings.SOURCE[0][0], null=True, blank=True)
    money_spent = models.PositiveIntegerField()
    money_source = models.CharField(max_length=10, choices=settings.BANKS, default=settings.BANKS[1][0], null=True, blank=True)
    expense_category = models.CharField(max_length=20, choices=settings.CATEGORY, default=settings.CATEGORY[3][0])
    description = models.CharField(max_length=200, default=None, null=True)
    purchase_date = models.DateField()

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return str(self.id)

# class ChainMoney(models.Model):

load_amount/forms.py
from django import forms
from .models import Money


class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Money
        fields = ['money_spent', 'money_source', 'expense_category', 'description', 'purchase_date', 'expense_link', 'income_link', 'chain_link', 'loan_link', 'withdraw_link']

load_amount/views.py
from django.shortcuts import render
from .models import Money
from .forms import ExpenseForm
from user.models import UserProfile
from django.http import HttpResponseRedirect, HttpResponse
from all_view.views import all_list_rest
from django.contrib.auth.decorators import login_required
from cashwithdrawl.forms import CashWithdrawlForm
from django.http import JsonResponse
from django.http import QueryDict

# Create your views here.
@login_required
def index(request):
    return HttpResponseRedirect('index')

def get_data(request):
    all_data = Money.objects.all()
    return render(request, 'app/load_index.html', {'posts':all_data})

# @login_required
def form_data(request):
    # request.user.id = 1
    user = UserProfile.objects.get(user_id=request.user.id)
    if request.method == "POST":
        category = request.POST.get('expense_category')
        if category == "cash_with":
            req_copy = request.POST.copy()
            user_dict = {'user': request.user.id}
            req_copy.update(user_dict)
            form = CashWithdrawlForm(req_copy)

            if form.is_valid():
                form.save()
                user.commits += 1
                user.save()
                return JsonResponse({"status": 200, "message":"successfully uploaded"})
        else:
            form = ExpenseForm(request.POST)
            if form.is_valid():
                form.save()
                user.commits += 1
                user.save()
                return JsonResponse({"status": 200, "message":"successfully uploaded"})
    else:
        form = ExpenseForm()
    income_form, load_form, chain_form, loan_form, returns_form = all_list_rest()
    return render(request,'app/load_expense.html',{'form':form, 'income_form':income_form, 'load_form':load_form,
                                                   'chain_form':chain_form, 'loan_form': loan_form,'returns_form':returns_form})


def update(request, id):
    data = Money.objects.get(id=id)
    data.money_spent = request.POST['money_spent']
    data.money_source = request.POST['money_source']
    data.expense_category = request.POST['expense_category']
    data.description = request.POST['description']
    data.purchase_date = request.POST['purchase_date']
    data.save()
    return JsonResponse({"status": 200, "message":"successfully updated"})

load_amount/templates/app/load_expense.html
{% extends "load_base.html" %}

{% block title %}Load Expense{% endblock %}

{% block content %}
    <h1> Load new expense report </h1>
    <form action="/expense/load_expense" method="post" id="expense" novalidate>
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="submit">
    </form>

    <script type = "text/javascript">
        $(document).ready(function() {
            $('label[for="id_income_link"]').show();$("#id_income_link").show();
            $('label[for="id_chain_link"]').hide();$("#id_chain_link").hide();
            $('label[for="id_loan_link"]').hide();$("#id_loan_link").hide();
         });
        $('#id_expense_link').on('change',function(){
            if( $(this).val()==="income"){
               $('label[for="id_income_link"]').show();$("#id_income_link").show();
                $('label[for="id_chain_link"]').hide();$("#id_chain_link").hide();
                $('label[for="id_loan_link"]').hide();$("#id_loan_link").hide();
            } else if( $(this).val()==="chain") {
                 $('label[for="id_income_link"]').hide();$("#id_income_link").hide();
                $('label[for="id_chain_link"]').show();$("#id_chain_link").show();
                $('label[for="id_loan_link"]').hide();$("#id_loan_link").hide();
            } else if( $(this).val()==="loan") {
                 $('label[for="id_income_link"]').hide();$("#id_income_link").hide();
                $('label[for="id_chain_link"]').hide();$("#id_chain_link").hide();
                $('label[for="id_loan_link"]').show();$("#id_loan_link").show();
            }
        });
    </script>

{% endblock %}

load_amount/templates/app/load_index.html
{% extends "load_base.html" %}

{% block title %}Expenses Report{% endblock %}

{% block content %}
    <h1> Expense </h1>
    {% for post in posts %}
        <p> {{ post.money_spent }} <br /> {{ post.money_source }}</p>
    {% endfor %}
{% endblock %}